name: PR Merged

on:
  pull_request:
    types: [closed]

jobs:
  start:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx pnpm i
      - name: Update README
        run: npm run build
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          ref: main
          message: 'chore: update readme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
